// Code generated by hertz generator.

package social

import (
	"context"
	"work4/biz/pack"
	"work4/biz/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"work4/biz/model/social"
)

// Star .
// @router /relation/action [POST]
func Star(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.StarRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.StarResponse)

	err = service.NewSocialService(ctx, c).Star(&req)

	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(nil)

	pack.SendResponse(c, resp, consts.StatusOK)
}

// StarList .
// @router /like/list [GET]
func StarList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.StarListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.StarListResponse)

	socialResp, count, err := service.NewSocialService(ctx, c).StarList(&req)

	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(nil)
	resp.Data = pack.UserInfoList(socialResp, count)

	pack.SendResponse(c, resp, consts.StatusOK)
}

// FanList .
// @router /follower/list [GET]
func FanList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FanListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.FanListResponse)

	socialResp, count, err := service.NewSocialService(ctx, c).FanList(&req)

	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(nil)
	resp.Data = pack.UserInfoList(socialResp, count)

	pack.SendResponse(c, resp, consts.StatusOK)
}

// FriendList .
// @router /friends/list [GET]
func FriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FriendListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(social.FriendListResponse)

	socialResp, count, err := service.NewSocialService(ctx, c).FriendList(&req)

	if err != nil {
		pack.SendFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(nil)
	resp.Data = pack.UserInfoList(socialResp, count)

	pack.SendResponse(c, resp, consts.StatusOK)
}
