// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"work4/biz/dal"
	"work4/biz/middleware"
	"work4/bootstrap/env"
)

func Init() {
	env.Init()
	dal.Init()
	middleware.Init()
}

func main() {

	Init()

	h := server.Default(server.WithHostPorts("0.0.0.0:10001"))

	register(h)
	h.Spin()
}
