// Code generated by hertz generator.

package video

import (
	"github.com/cloudwego/hertz/pkg/app"
	"work4/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _uploadlistMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _rankMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}
