// Code generated by hertz generator.

package video

import (
	"context"
	"work4/biz/pack"
	"work4/biz/service"
	"work4/pkg/errmsg"

	"github.com/cloudwego/hertz/pkg/app"
	"work4/biz/model/video"
)

// Upload .
// @router /video/publish [POST]
func Upload(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.UploadRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	videodata, err := c.FormFile("videodata")
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	coverdata, err := c.FormFile("coverdata")
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(video.UploadResponse)

	err = service.NewVideoService(ctx, c).UploadVideo(videodata, coverdata, &req)

	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(errmsg.NoError)

	pack.SendResponse(c, resp)
}

// UploadList .
// @router /video/list [GET]
func UploadList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.UploadListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(video.UploadListResponse)

	videoResp, count, err := service.NewVideoService(ctx, c).UploadList(&req)

	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(errmsg.NoError)
	resp.Data = pack.VideoList(videoResp, count)

	pack.SendResponse(c, resp)
}

// Rank .
// @router /video/popular [GET]
func Rank(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.RankRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(video.RankResponse)

	videoResp, err := service.NewVideoService(ctx, c).Rank(&req)

	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(errmsg.NoError)
	resp.Data = pack.VideoList(videoResp, 100)

	pack.SendResponse(c, resp)
}

// Query .
// @router /video/search [POST]
func Query(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.QueryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(video.QueryResponse)

	videoResp, count, err := service.NewVideoService(ctx, c).Query(&req)

	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(errmsg.NoError)
	resp.Data = pack.VideoList(videoResp, count)

	pack.SendResponse(c, resp)
}

// Feed .
// @router /video/feed [POST]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.FeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(video.FeedResponse)

	videoResp, count, err := service.NewVideoService(ctx, c).Feed(&req)

	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(errmsg.NoError)
	resp.Data = pack.VideoList(videoResp, count)

	pack.SendResponse(c, resp)
}
