// Code generated by hertz generator.

package user

import (
	"context"
	"work4/biz/middleware/jwt"
	"work4/biz/pack"
	"work4/biz/service"
	"work4/pkg/errmsg"

	"github.com/cloudwego/hertz/pkg/app"
	"work4/biz/model/user"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.RegisterResponse)

	userResp, err := service.NewUserService(ctx, c).Register(&req)

	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(errmsg.NoError)
	resp.Data = pack.User(userResp)
	pack.SendResponse(c, resp)
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.LoginResponse)

	userResp, err := service.NewUserService(ctx, c).Login(&req)

	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	jwt.AccessTokenJwtMiddleware.LoginHandler(ctx, c)
	jwt.RefreshTokenJwtMiddleware.LoginHandler(ctx, c)

	resp.Base = pack.BuildBaseResp(errmsg.NoError)
	resp.Data = pack.UserInfoDetail(userResp)
	c.Header("Access-Token", c.GetString("Access-Token"))
	c.Header("Refresh-Token", c.GetString("Refresh-Token"))

	pack.SendResponse(c, resp)
}

// Info .
// @router /user/info [GET]
func Info(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.InfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.InfoResponse)

	userResp, err := service.NewUserService(ctx, c).GetInfo(&req)

	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(errmsg.NoError)
	resp.Data = pack.UserInfoDetail(userResp)

	pack.SendResponse(c, resp)
}

// Upload .
// @router /user/avatar/oss [PUT]
func Upload(ctx context.Context, c *app.RequestContext) {
	var err error
	data, err := c.FormFile("data")
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.UploadResponse)

	userResp, err := service.NewUserService(ctx, c).UploadAvatar(data)

	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(errmsg.NoError)
	resp.Data = pack.User(userResp)

	pack.SendResponse(c, resp)
}

// MFAGet .
// @router /auth/mfa/qrcode [GET]
func MFAGet(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.MFAGetRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.MFAGetResponse)

	userResp, err := service.NewUserService(ctx, c).MFAGet()

	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(errmsg.NoError)
	resp.Data = pack.MFA(userResp)

	pack.SendResponse(c, resp)
}

// MFA .
// @router /auth/mfa/bind [POST]
func MFA(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.MFABindRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.MFABindResponse)

	err = service.NewUserService(ctx, c).MFABind(&req)

	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.Base = pack.BuildBaseResp(errmsg.NoError)

	pack.SendResponse(c, resp)
}
